image:
  file: ./scripts/dev-image/.gitpod.Dockerfile

tasks:
  - name: Supervisor (VNC and noVNC)
    command: /usr/bin/supervisord --configuration /etc/supervisord.conf &
  - name: Set cache path and warm it up
    init: |
      echo "build --repository_cache=/workspace/.cache/bazel-repo" >> /workspace/selenium/.bazelrc.local
      echo "test --repository_cache=/workspace/.cache/bazel-repo" >> /workspace/selenium/.bazelrc.local
      echo "build --disk_cache=/workspace/.cache/bazel-disk" >> /workspace/selenium/.bazelrc.local
      echo "test --disk_cache=/workspace/.cache/bazel-disk" >> /workspace/selenium/.bazelrc.local
      bazel build grid
