env:
  global:
    - DISPLAY=:99.0
    - PYTEST_ADDOPTS=--verbose --instafail
matrix:
  include:
    - language: java
      jdk: oraclejdk8
      env: TASK=build
      addons:
        apt:
          packages:
            - oracle-java8-installer
    - language: python
      python: 2.7
      env: TOXENV=py27-chrome
      addons:
        apt:
          packages:
            - oracle-java8-installer
    - language: python
      python: 2.7
      env: TOXENV=py27-firefox
      addons:
        apt:
          packages:
            - oracle-java8-installer
        firefox: latest-esr
    - language: python
      python: 2.7
      env: TOXENV=py27-marionette
      addons:
        apt:
          packages:
            - oracle-java8-installer
        firefox: latest
    - language: python
      python: 2.7
      env: TOXENV=py27-phantomjs
      addons:
        apt:
          packages:
            - oracle-java8-installer
    - language: python
      python: 2.7
      env: TOXENV=py27-remote
      addons:
        apt:
          packages:
            - oracle-java8-installer
        firefox: latest
    - language: python
      python: 3.5
      env: TOXENV=py35-chrome
      addons:
        apt:
          packages:
            - oracle-java8-installer
    - language: python
      python: 3.5
      env: TOXENV=py35-firefox
      addons:
        apt:
          packages:
            - oracle-java8-installer
        firefox: latest-esr
    - language: python
      python: 3.5
      env: TOXENV=py35-marionette
      addons:
        apt:
          packages:
            - oracle-java8-installer
        firefox: latest
    - language: python
      python: 3.5
      env: TOXENV=py35-phantomjs
      addons:
        apt:
          packages:
            - oracle-java8-installer
    - language: python
      python: 3.5
      env: TOXENV=py35-remote
      addons:
        apt:
          packages:
            - oracle-java8-installer
        firefox: latest
    - language: ruby
      rvm: 2.2.3
      jdk: oraclejdk8
      env: TASK=//rb:unit-test
      addons:
        apt:
          packages:
            - oracle-java8-installer
    - language: ruby
      rvm: 2.2.3
      jdk: oraclejdk8
      env: TASK=//rb:chrome-test
      addons:
        apt:
          packages:
            - oracle-java8-installer
    - language: ruby
      rvm: 2.2.3
      jdk: oraclejdk8
      env: TASK=//rb:firefox-test
      addons:
        apt:
          packages:
            - oracle-java8-installer
        firefox: latest
    - language: ruby
      rvm: 2.2.3
      jdk: oraclejdk8
      env: TASK=//rb:ff-legecy-test
      addons:
        apt:
          packages:
            - oracle-java8-installer
        firefox: latest-esr
    - language: ruby
      rvm: 2.2.3
      jdk: oraclejdk8
      env: TASK=//rb:phantomjs-test
      addons:
        apt:
          packages:
            - oracle-java8-installer
    - language: ruby
      rvm: 2.2.3
      jdk: oraclejdk8
      env: TASK=//rb:remote-chrome-test
      addons:
        apt:
          packages:
            - oracle-java8-installer
    - language: ruby
      rvm: 2.2.3
      jdk: oraclejdk8
      env: TASK=//rb:remote-firefox-test
      addons:
        apt:
          packages:
            - oracle-java8-installer
        firefox: latest
    - language: ruby
      rvm: 2.2.3
      jdk: oraclejdk8
      env: TASK=//rb:remote-ff-legacy-test
      addons:
        apt:
          packages:
            - oracle-java8-installer
        firefox: latest-esr
    - language: ruby
      rvm: 2.2.3
      jdk: oraclejdk8
      env: TASK=//rb:remote-phantomjs-test
      addons:
        apt:
          packages:
            - oracle-java8-installer
install: ./scripts/travis/install.sh
before_script: ./scripts/travis/before_script.sh
script: ./scripts/travis/script.sh
notifications:
  email: false
  irc:
    channels:
      - secure: K+Wuro8Y/66zt9truTZuZzFmPqiGrFsH/sPzOBDK3+57mL6/vg2NoQCXOTq3U5RLdVKavlvZcm6+9nsNncVPRgzL7ORuW3BgLaBJis3lTA13AqlOnAbXcYytQEulVeWmvPipHFFFqaHs/z77lxm4fKwAAuBnK1f+mXKZDZR2hLo=
    on_success: never
    on_failure: always
    use_notice: true
    skip_join: true
