name: 'Setup Chrome and chromedriver'
runs:
  using: "composite"
  steps:
    - run: |
        sudo apt install wget software-properties-common apt-transport-https
        sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
        sudo apt-get update -qqy
        sudo apt-get -qqy install microsoft-edge-stable
        EDGE_VERSION=$(microsoft-edge-stable --version)
        EDGE_FULL_VERSION=${EDGE_VERSION%%.*}
        EDGE_MAJOR_VERSION=${EDGE_FULL_VERSION//[!0-9]}

        MS_STORAGE=https://msedgewebdriverstorage.blob.core.windows.net/edgewebdriver
        EDGEDRIVER_VERSION=`curl -s ${MS_STORAGE}/LATEST_RELEASE_${EDGE_MAJOR_VERSION}_LINUX | LC_CTYPE=C tr -cd [.0-9]`
        curl -LO ${MS_STORAGE}/${EDGEDRIVER_VERSION}/edgedriver_linux64.zip

        unzip edgedriver_linux64.zip && chmod +x msedgedriver && sudo mv msedgedriver /usr/local/bin
        msedgedriver -version
      shell: bash
