name: CI - .NET

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/bazel.yml
    with:
      name: Build
      cache-key: false
      os: windows
      run: |
        bazel build //dotnet/src/webdriver
        bazel build //dotnet/src/support

  integration-tests:
    name: Browser Tests
    needs: build
    uses: ./.github/workflows/bazel.yml
    with:
      name: Browser Tests
      cache-key: dotnet-test-all
      os: windows
      run: |
        bazel test //dotnet/test/common/... --pin_browsers=true
