name: CI - .NET

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/bazel.yml
    with:
      name: Build
      cache-key: false
      os: windows
      run: |
        bazel build //dotnet/src/webdriver
        bazel build //dotnet/src/support

  integration-tests:
    name: Browser Tests
    needs: build
    uses: ./.github/workflows/bazel.yml
    with:
      name: Validation Tests
      cache-key: dotnet-validation
      java-version: 17
      os: windows
      run: |
        bazel test --keep_going //dotnet/test/common:DotNetValidationTest-net6.0 //dotnet/test/common:DotNetValidationTest-net48
