name: CI - Java

on:
  workflow_call:
  workflow_dispatch:

jobs:
  browser-tests:
    name: Browser Tests
    uses: ./.github/workflows/bazel.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows
          - os: macos
    with:
      name: Browser Tests (chrome, ${{ matrix.os }})
      os: ${{ matrix.os }}
      browser: chrome
      cache-key: java-${{ matrix.os }}-tests
      run: |
        if [[ "${{ matrix.os }}" == "windows" ]]; then
          bazel test //java/test/org/openqa/selenium/chrome:ChromeDriverFunctionalTest ^
              //java/test/org/openqa/selenium/federatedcredentialmanagement:FederatedCredentialManagementTest ^
              //java/test/org/openqa/selenium/firefox:FirefoxDriverBuilderTest ^
              //java/test/org/openqa/selenium/grid/gridui:OverallGridTest ^
              //java/test/org/openqa/selenium/grid/router:RemoteWebDriverDownloadTest ^
              //java/test/org/openqa/selenium/remote:RemoteWebDriverBuilderTest ^
              //java/test/org/openqa/selenium/grid/router:RemoteWebDriverDownloadTest
        else
          bazel test //java/test/org/openqa/selenium/chrome:ChromeDriverFunctionalTest-remote \
              //java/test/org/openqa/selenium/federatedcredentialmanagement:FederatedCredentialManagementTest \
              //java/test/org/openqa/selenium/firefox:FirefoxDriverBuilderTest \
              //java/test/org/openqa/selenium/grid/gridui:OverallGridTest \
              //java/test/org/openqa/selenium/grid/router:RemoteWebDriverDownloadTest \
              //java/test/org/openqa/selenium/remote:RemoteWebDriverBuilderTest \
              //java/test/org/openqa/selenium/grid/router:RemoteWebDriverDownloadTest
        fi

  remote-tests:
    name: Remote Tests
    uses: ./.github/workflows/bazel.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows
          - os: macos
    with:
      name: Remote Tests (chrome, ${{ matrix.os }})
      os: ${{ matrix.os }}
      browser: chrome
      cache-key: java-${{ matrix.os }}-remote-tests
      run: |
        if [[ "${{ matrix.os }}" == "windows" ]]; then
          bazel test //java/test/org/openqa/selenium/chrome:ChromeDriverFunctionalTest-remote ^
              //java/test/org/openqa/selenium/grid/router:RemoteWebDriverDownloadTest-remote
        else
          bazel test //java/test/org/openqa/selenium/chrome:ChromeDriverFunctionalTest-remote \
              //java/test/org/openqa/selenium/grid/router:RemoteWebDriverDownloadTest-remote
        fi
