name: CI - RBE

on:
  workflow_call:
  workflow_dispatch:

jobs:
  rbe-small-tests:
    name: RBE - Small Tests
    uses: ./.github/workflows/bazel.yml
    with:
      name: Cache
      cache-key: rbe
      disk-cache: false
      run: bazel test --config=remote --keep_going //java/...
