name: Dispatch

on:
  workflow_dispatch:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  check_java:
    uses: ./.github/workflows/should-workflow-run.yml
    with:
      bazel-target-prefix: '//java'

  run_java:
    uses: ./.github/workflows/java.yml
    needs: check_java_workflow
    if: ${{ needs.check_java_workflow.outputs.result == 'true' }}

