name: JavaScript workflow

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  build:
    # Skip job based on the commit message, only works in push to branches for now
    if: contains(toJson(github.event.commits), '[skip ci]') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v1
      - name: Node.js Setup
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Setup bazelisk
        uses: ./.github/actions/setup-bazelisk
      - name: Run JavaScript tests
        run: bazel test //javascript/node/selenium-webdriver:tests
        env:
          MARIONETTE: 1
          SELENIUM_BROWSER: firefox
          NPM: test
