name: Java CI

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '15 9,21 * * *'

env:
  NODE_VERSION: '13.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v2
      - name: Cache Bazel artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel-disk
            ~/.cache/bazel-repo
          key: ${{ runner.os }}-bazel-build-${{ hashFiles('**/BUILD.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-build-
      - name: Setup bazelisk
        uses: ./.github/actions/setup-bazelisk
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build grid
        uses: ./.github/actions/bazel
        with:
          command: build grid
