name: Java CI

on:
  workflow_dispatch:
  schedule:
    - cron: '15 9,21 * * *'

env:
  NODE_VERSION: '13.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Setup bazelisk
        uses: ./.github/actions/setup-bazelisk
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Sets commit range
        run: echo "COMMIT_RANGE=HEAD^..HEAD" >> $GITHUB_ENV
      - name: Check if workflow should run
        id: should-workflow-run
        uses: ./.github/actions/should-workflow-run
        with:
          bazel-target-prefix: "//java"
