name: Should workflow run?

on:
  workflow_call:
    inputs:
      commit-range:
        description: Commits considered to determine bazel targets
        required: false
        type: string
        default: HEAD^..HEAD
      bazel-target-prefix:
        description: Bazel target prefix used to determine if the code path will be used
        required: true
        type: string

    outputs:
      result:
        description: Boolean to be used in the job to decide if the job runs or not
        value: ${{ jobs.check_workflow_run.outputs.result }}

jobs:
  check_workflow_run:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check-bazel-target-prefix.run-workflow }}
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Setup bazelisk
        uses: ./.github/actions/setup-bazelisk
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Copy bazelrc
        run: cp .github/.bazelrc.local .
        shell: bash
      - name: Check bazel target prefix
        id: check-bazel-target-prefix
        run: |
          echo "::set-output name=run-workflow::true"
        shell: bash
#      - name: Check bazel target prefix
#        id: check-bazel-target-prefix
#        run: |
#          affected_files=$(git diff --name-only ${{ inputs.commit-range }})
#          bazel_targets=()
#          for bazel_target in $affected_files ; do
#            bazel_targets+=($(bazel query "$bazel_target"))
#            bazel query "$bazel_target"
#          done
#          echo "::set-output name=bazel-targets::${bazel_targets[*]}"
#          if [[ " ${bazel_targets[*]} " == *"$BAZEL_TARGET_PREFIX"* ]]; then
#            echo "::set-output name=run-workflow::true"
#          else
#            echo "::set-output name=run-workflow::false"
#          fi
#        shell: bash

#      - name: Check if workflow should run
#        id: check-workflow
#        uses: ./.github/actions/should-workflow-run
#        with:
#          bazel-target-prefix: ${{ inputs.bazel-target-prefix }}
#          commit-range: ${{ inputs.commit-range }}
